// Types
export type AppEventName = `${AppEvents}`;

// Enums
export enum AppEvents {
  AccessibilitySupportChanged = 'accessibility-support-changed',
  Activate = 'activate',
  ActivityWasContinued = 'activity-was-continued',
  BeforeQuit = 'before-quit',
  BrowserWindowBlur = 'browser-window-blur',
  BrowserWindowCreated = 'browser-window-created',
  BrowserWindowFocus = 'browser-window-focus',
  CertificateError = 'certificate-error',
  ContinueActivity = 'continue-activity',
  ContinueActivityError = 'continue-activity-error',
  DesktopCapturerGetSources = 'desktop-capturer-get-sources',
  GpuInfoUpdate = 'gpu-info-update',
  GpuProcessCrashed = 'gpu-process-crashed',
  Login = 'login',
  NewWindowForTab = 'new-window-for-tab',
  OpenFile = 'open-file',
  OpenUrl = 'open-url',
  Quit = 'quit',
  Ready = 'ready',
  RemoteGetBuiltin = 'remote-get-builtin',
  RemoteGetCurrentWebContents = 'remote-get-current-web-contents',
  RemoteGetCurrentWindow = 'remote-get-current-window',
  RemoteGetGlobal = 'remote-get-global',
  RemoteRequire = 'remote-require',
  RenderProcessGone = 'render-process-gone',
  RenderProcessCrashed = 'renderer-process-crashed',
  SecondInstance = 'second-instance',
  SelectClientCertificate = 'select-client-certificate',
  SessionCreated = 'session-created',
  UpdateActivityState = 'update-activity-state',
  WebContentsCreated = 'web-contents-created',
  WillContinueActivity = 'will-continue-activity',
  WillFinishLaunching = 'will-finish-launching',
  WillQuit = 'will-quit',
  WindowAllClosed = 'window-all-closed',
}
